### ISSUE TITLE
Typo in Linux 0x0F Bonus: PS1

### ISSUE THREAD

**Issue by lukasz-kukulka** [coders-school/linux#106]
Typo in [Linux 0x0F Bonus: PS1](https://kursy.coders.school/szkolenie.html?tid=14&lid=226) 

> Wklejenie powyższego do pliku ~/.bashrc spowoduje, że w linia zachęty będzie mieć formę:

should be: 

> Wklejenie powyższego do pliku ~/.bashrc spowoduje, że linia zachęty będzie mieć formę:

**Comment by ziobron** [comment]
🏅 2 XP granted for @lukasz-kukulka
Thanks for raising this Issue to help to make the course better!
