### ISSUE TITLE
I'm as an unknown user

### ISSUE THREAD

**Issue by krzychtof** [coders-school/linux#136]
Hi,
I noticed that I was added to the STANDARD group, but it still appears as UNKNOWN USER. I understand that after being accepted into the 2021 group it will change to my nickname? Thank you
greetings / krzychtof

**Comment by ziobron** [comment]
🏅 2 XP granted for @krzychtof
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Hi, if you have a Standard then everything is fine. My situation do not remove the Unknown User label.
Under this Issue I will add this functionality. I will keep it open until I finish it.

**Comment by krzychtof** [comment]
ok, I understand, Thank You
BR / Krzysiek

śr., 19 maj 2021 o 22:29 Łukasz Ziobroń ***@***.***>
napisał(a):

**Comment by ziobron** [comment]
I have just fixed this problem. Not the "Unknown User" label should be removed after the user has added itself to the database by fulfilling the form and editing the Pull Request.
