### ISSUE TITLE
second check for creating directory failed, line count failed

### ISSUE THREAD

**Issue by jux1e** [coders-school/linux#172]
Hi I think there is a problem with checking script.
as you can see first check for creating dir passed but second failed despise it being the same command.

Also line count fails check fails I think because I passed to file only the number of lines. 

Here's link to check page:
https://github.com/coders-school/linux/runs/4926522974?check_suite_focus=true

**Comment by ziobron** [comment]
🏅 2 XP granted for @jux1e
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
I guess you are right. Thanks, we will take a look on Thursday. Just wait, please :)

**Comment by Penthurion** [comment]
Issue has been fixed :)
