### ISSUE TITLE
Add directory/processes.txt

### ISSUE THREAD

**Issue by BarTes8** [coders-school/linux#41]
Since in the task 2 isn't precised that one needs to be in the new created directory.
https://github.com/coders-school/linux/pull/30/commits/4db787fb70f8b0d69035dbc60c54e0b4a6cac972

**Comment by ziobron** [comment]
Linking #76. The same issue.

**Comment by ziobron** [comment]
🏅 2 XP granted for @BarTes8 
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Fixed in 181c3e4
