### ISSUE TITLE
`ps aux` does not give any /bin results on Windows 

### ISSUE THREAD

**Issue by ziobron** [coders-school/linux#50]
Occured in #27

**Comment by michantoniuk** [comment]
Same in my case (WSL2/Ubuntu 20.04).
Any workaround?

**Comment by ziobron** [comment]
Linking #54 
The script just accept empty results, so looks like not a big deal for now, but I will check how it can be improved this week.

**Comment by ziobron** [comment]
The solution for this is... just run all the commands and accept an empty output. Simply do not replace the commands, just look for /bin. The script should work fine with that. I have updated the homework to indicate that it is ok.
